/**
 * Downloads the self-hosted webfonts and regenerates `src/styles/fonts.css`.
 *
 * Only the Latin and Latin Extended subsets are kept — Latin Extended carries
 * the French accents Canadian copy needs, and the other subsets Google ships
 * (Cyrillic, Greek, Vietnamese) would never be used.
 *
 * Run with `npm run fonts` if a family, weight or subset changes.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import { join } from 'node:path'

const OUT = 'public/fonts'
const CSS = 'src/styles/fonts.css'
const SUBSETS = new Set(['latin', 'latin-ext'])

const API =
  'https://fonts.googleapis.com/css2?family=Anton&family=Archivo:wght@400;600;700' +
  '&family=Barlow+Condensed:wght@700&display=swap'

// Google serves woff2 only to browsers that advertise support.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36'

const FILE_NAMES = { Anton: 'anton', Archivo: 'archivo', 'Barlow Condensed': 'barlow-condensed' }
// Archivo is a variable font: one file covers the whole weight range.
const WEIGHTS = { Anton: '400', Archivo: '100 900', 'Barlow Condensed': '700' }

const css = await (await fetch(API, { headers: { 'User-Agent': UA } })).text()

const faces = []
const seen = new Set()
for (const [, subset, block] of css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
  if (!SUBSETS.has(subset)) continue
  const family = block.match(/font-family: '([^']+)'/)[1]
  const key = `${family}:${subset}`
  if (seen.has(key)) continue
  seen.add(key)
  faces.push({
    family,
    subset,
    file: `${FILE_NAMES[family]}-${subset}.woff2`,
    url: block.match(/url\((https:\/\/[^)]+)\)/)[1],
    unicodeRange: block.match(/unicode-range: ([^;]+);/)[1],
  })
}

await mkdir(OUT, { recursive: true })

for (const face of faces) {
  const response = await fetch(face.url, { headers: { 'User-Agent': UA } })
  const bytes = Buffer.from(await response.arrayBuffer())
  await writeFile(join(OUT, face.file), bytes)
  console.log(`${face.file.padEnd(34)} ${(bytes.length / 1024).toFixed(1)} kB`)
}

const header = `/*
 * Self-hosted webfonts. Generated by \`npm run fonts\` — do not edit by hand.
 *
 * Latin and Latin Extended subsets only (Latin Extended covers French accents
 * for Canadian copy). Archivo is a variable font: one file serves every weight.
 */
`

const body = faces
  .map((face) =>
    [
      '@font-face {',
      `  font-family: '${face.family}';`,
      '  font-style: normal;',
      `  font-weight: ${WEIGHTS[face.family]};`,
      '  font-display: swap;',
      `  src: url('/fonts/${face.file}') format('woff2');`,
      `  unicode-range: ${face.unicodeRange};`,
      '}',
    ].join('\n'),
  )
  .join('\n\n')

await writeFile(CSS, `${header}\n${body}\n`)
console.log(`\nwrote ${CSS} (${faces.length} faces)`)
