/**
 * Responsive product photography.
 *
 * Files are generated by `npm run images` from the full-resolution originals in
 * `assets-source/` and served from `public/img/` under stable names, so the hero
 * shot can be preloaded from the HTML rather than waiting for React to render.
 */

const base = import.meta.env.BASE_URL

function url(file: string): string {
  return `${base}img/${file}`
}

export interface ResponsiveImage {
  src: string
  srcSet: string
  /** Intrinsic size of `src`, so the browser can reserve the space. */
  width: number
  height: number
}

function set(name: string, widths: number[], aspect: number): ResponsiveImage {
  const largest = widths[widths.length - 1]!
  return {
    src: url(`${name}-${largest}.webp`),
    srcSet: widths.map((w) => `${url(`${name}-${w}.webp`)} ${w}w`).join(', '),
    width: largest,
    height: Math.round(largest / aspect),
  }
}

/** 0W-20 Premium Full Synthetic 5 L jug, front. */
export const JUG_FRONT = set('jug-front', [340, 520, 860], 1023 / 1600)

/** Back label showing features, benefits and approvals. */
export const JUG_BACK = set('jug-back', [400, 750], 1009 / 1600)

/** Preload target for the homepage hero — the page's LCP element. */
export const HERO_IMAGE_HREF = url('jug-front-860.webp')
